dnshare/blueprints/default/models.py
from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship

from dnshare.extensions import db


class DomainRegistration(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    subdomain = db.Column(db.String, nullable=False)
    domain = db.Column(db.String, nullable=False)
    host_ip = db.Column(db.String(15), nullable=False)
    creator_ip = db.Column(db.String(15), nullable=False)
    creation_date_utc = db.Column(db.DateTime, nullable=False)
    expiration_date_utc = db.Column(db.DateTime, nullable=False)
    is_active = db.Column(db.Boolean, nullable=False)

    user_id = db.Column(db.Integer, ForeignKey('user.id'), nullable=True)
    user = relationship("User", back_populates="registrations")

    def __repr__(self):
        return (f'<DomainRegistration {self.id} {self.subdomain}.{self.domain}'
                f' => {self.host_ip} by {self.creator_ip}>')

dnshare/blueprints/default/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, IntegerField
from wtforms.validators import DataRequired, ValidationError


class AnonRegisterForm(FlaskForm):
    SUBDOMAIN_REQUIRED_MSG = "The subdomain is required."
    DOMAIN_REQUIRED_MSG = "Selecting a domain is required."
    HOST_IP_REQUIRED_MSG = "The IP to which the name will resolve is required."

    subdomain = StringField(
        'Subdomain', validators=[DataRequired(SUBDOMAIN_REQUIRED_MSG)])
    domain = SelectField(
        'Domain', validators=[DataRequired(DOMAIN_REQUIRED_MSG)])
    host_ip = StringField(
        'Host IP', validators=[DataRequired(HOST_IP_REQUIRED_MSG)])

    def validate_subdomain(form, field):
        # We have to check for protected subdomains too.
        if field.data in ["www", "@"]:
            raise ValidationError("protected_subdomain")


class ClaimForm(FlaskForm):
    registration_id = IntegerField('Registration ID',
                                   validators=[DataRequired()])


class DeleteForm(FlaskForm):
    registration_id = IntegerField('Registration ID',
                                   validators=[DataRequired()])

dnshare/blueprints/default/__init__.py
from .views import default  # noqa

dnshare/blueprints/default/views.py
from flask import Blueprint, render_template, make_response, flash, \
    redirect, url_for, request
from flask_login import current_user, login_required

from dnshare.gateways import InvalidIPv4HostAddress, InvalidSubdomainError
from .application import register_subdomain, registration_overriden, \
    SubdomainAlreadyTaken, RegistrationLimitSurpassed, \
    get_claimable_registrations, get_user_registrations, claim_anon_registration, \
    delete_registration
from .forms import AnonRegisterForm, ClaimForm, DeleteForm

default = Blueprint('default', __name__, template_folder='templates')

SUBMIT_ERROR_MSG = ('It appears that there are some errors with your '
                    'registration. Please check and try again.')
REGISTRATION_OK_TPL = ('{subdomain}.{domain} was successfully '
                       'registered to resolve to {host_ip}.')
TOO_MANY_REGISTRATIONS_MSG = 'You have registered quite a few domains today. Please try again tomorrow.'
NGGYU_URL = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'
INVALID_HOST_TPL = ('The host "{host}" apparently is not a valid IPv4. '
                    'Please check that and try again.')
INVALID_SUBDOMAIN_TPL = ('The subdomain "{subdomain}" doesn\'t appear to be '
                         'a valid subdomain. Please check that and try again.')


@default.route("/", methods=['GET'])
def home():
    form = _create_anon_register_form()
    remote_ip = request.remote_addr

    return render_template('default/home.html', form=form, remote_ip=remote_ip)


@default.route('/', methods=['POST'])
def register_anon_host():
    form = _create_anon_register_form()
    if not form.validate():
        if "protected_subdomain" in form.subdomain.errors:
            return redirect(NGGYU_URL)

        home_page = render_template('default/home.html', form=form)
        return make_response(home_page, 400)

    subdomain = form.subdomain.data
    domain = form.domain.data
    host_ip = form.host_ip.data
    creator_ip = request.environ.get('HTTP_X_REAL_IP', request.remote_addr)

    def handle_reregistration(sender, old_host_ip):
        msg = _create_override_msg(subdomain, domain, old_host_ip, host_ip)
        flash(msg, 'info')

    registration_overriden.connect(handle_reregistration)

    try:
        is_anon = current_user.is_anonymous
        register_subdomain(subdomain, domain, host_ip, creator_ip,
                           None if is_anon else current_user)
    except SubdomainAlreadyTaken:
        taken_msg = _create_already_taken_msg(subdomain, domain)
        flash(taken_msg, 'error')
        return redirect(url_for('default.home'))
    except RegistrationLimitSurpassed:
        flash(TOO_MANY_REGISTRATIONS_MSG, 'error')
        return redirect(url_for('default.home'))
    except InvalidIPv4HostAddress:
        host_error = _create_invalid_host_msg(host_ip)
        flash(host_error, 'error')
        return redirect(url_for('default.home'))
    except InvalidSubdomainError:
        error = _create_invalid_subdomain_msg(subdomain)
        flash(error, 'error')
        return redirect(url_for('default.home'))

    success_message = _create_success_msg(
        form.subdomain.data, form.domain.data, form.host_ip.data)
    flash(success_message, 'success')

    return redirect(url_for('default.home'))


@default.route('/registrations', methods=['GET'])
@login_required
def registrations():
    user_ip = request.environ.get('HTTP_X_REAL_IP', request.remote_addr)
    user_id = current_user.id

    claimable_registrations = get_claimable_registrations(user_ip)
    active_registrations = get_user_registrations(user_id)

    return render_template('default/my_domains.html',
                           claimable=claimable_registrations,
                           active=active_registrations)


@default.route('/claim', methods=['POST'])
@login_required
def claim():
    user_ip = request.environ.get('HTTP_X_REAL_IP', request.remote_addr)
    user_id = current_user.id

    form = ClaimForm()
    if form.validate():
        claim_anon_registration(user_id, user_ip, form.registration_id.data)

    flash('Registration has been claimed successfully!', 'success')
    return redirect(url_for('default.registrations'))


@default.route('/delete', methods=['POST'])
@login_required
def delete():
    user_id = current_user.id

    form = DeleteForm()
    if form.validate():
        delete_registration(user_id, form.registration_id.data)

    flash('Registration has been deleted. Change may take up to 1 hour '
          'to propagate to DNS servers due to DNS caching.', 'success')
    return redirect(url_for('default.registrations'))


@default.route('/about', methods=['GET'])
def about():
    return render_template('default/about.html')


@default.route('/privacy', methods=['GET'])
def privacy():
    return render_template('default/privacy.html')


def _create_anon_register_form():
    form = AnonRegisterForm()
    form.domain.choices = [(d, d) for d in _get_available_domains()]
    return form


def _get_available_domains():
    """Get all available domains for which a user can register a
    subdomain. Currently hardcoded."""
    return ["dnshare.org"]


def _create_success_msg(subdomain, domain, host_ip):
    return REGISTRATION_OK_TPL.format(**locals())


def _create_override_msg(subdomain, domain, old_ip, new_ip):
    return (f'{subdomain}.{domain} updated! Previously it resolved to '
            f'{old_ip}, now it resolves to {new_ip}.')


def _create_already_taken_msg(subdomain, domain):
    return (f'{subdomain}.{domain} is already registered and active. '
            'Please choose other subdomain and domain combination.')


def _create_invalid_host_msg(host_ip):
    return INVALID_HOST_TPL.format(host=host_ip)


def _create_invalid_subdomain_msg(subdomain):
    return INVALID_SUBDOMAIN_TPL.format(subdomain=subdomain)

dnshare/blueprints/default/templates/default/about.html
{% extends "layout.html" %}
{% block body %}

    <h1 class="title is-2">
        DNShare.org / DNShare.club
    </h1>
    <h2 class="subtitle is-4">
        Free, temporary, and anonymous. A-host registration.
    </h2>

    <section class="content">
        <blockquote>
            DNShare is basically a place where anyone can register subdomains for two of the available shared domains,
            and get a free Let's Encrypt certificate with them.
        </blockquote>

        <p>
            It's aimed to teachers and beginner web developers who just want to point some name to an IP without further
            complication. You can optionally create an account if you want further control on how to manage your
            subdomain registrations.
        </p>

        <p>
            It's similar to <a href="https://freedns.afraid.org/">FreeDNS</a>, except in that FreeDNS has been around
            since forever, and it's likely to be around for years to come. And it that FreeDNS has a lot of other cool
            novelty domains too. Visit them and see for yourself!
        </p>

        <p>
            Anyways, feel free to create subdomains for any (legal) purpose. If you have any questions about the service
            feel free to send me an email at <code>cristian [at] dnshare.org</code>.
        </p>
    </section>

{% endblock %}

dnshare/blueprints/default/templates/default/home.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field_errors, render_flashed_messages %}
{% block body %}

    <div class="box" id="home-registration-form">
        <h1 class="title is-3">
            Register a new subdomain {% if current_user.is_anonymous %}anonymously{% endif %}
        </h1>
        <h2 class="subtitle is-5">
            {% if current_user.is_anonymous %}
                We still log your IP though, for the usual reasons.
            {% else %}
                And associate it with your user account.
            {% endif %}
        </h2>

        {{ render_flashed_messages() }}
        {{ render_field_errors(form) }}

        <form action="{{ url_for('default.register_anon_host') }}" id="anon-register-form" method="POST">
            {{ form.csrf_token }}

            <div class="field has-addons is-grouped is-grouped-multiline">
                <div class="control is-expanded">
                    <input id="subdomain-input" type="text" name="{{ form.subdomain.name }}"
                           placeholder="subdomain" class="input is-medium">
                </div>
                <div class="control is-expanded-mobile">
                    <div class="select is-medium">
                        <select name="{{ form.domain.name }}">
                            {% for domain in form.domain.choices %}
                                <option value="{{ domain[0] }}">{{ domain[1] }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="control is-hidden-mobile">
                <span class="button is-static is-medium">
                    resolves to
                </span>
                </div>
                <div class="control is-expanded-mobile">
                    <input type="text" name="{{ form.host_ip.name }}" class="input is-medium"
                           placeholder="127.0.0.1">
                </div>
            </div>

            <div class="level">
                <div class="level-left">
                    <p>
                        <strong>NOTE:</strong>
                        {% if current_user.is_authenticated %}
                            You'll be able to make changes to this registration as long as
                            you're logged in as <em>{{ current_user.email }}</em>, here,
                            or by going to My domains.
                        {% else %}
                            You'll be able to make changes to this registration from the following
                            IP: {{ remote_ip }}. For more reliable administration,
                            please consider creating an account and logging in.
                        {% endif %}
                    </p>
                </div>
                <div class="level-right">
                    <button type="submit" class="button is-primary is-medium is-fullwidth">
                        Submit registration
                    </button>
                </div>
            </div>
        </form>
    </div>

    <section class="columns has-text-centered">
        <div class="column">
            <h3 class="title is-4">For Teachers</h3>
            <h4 class="subtitle is-6 has-text-grey-light">Create one-off domains for examples.</h4>
        </div>
        <div class="column">
            <h3 class="title is-4 has-text-centered">For Lazy People</h3>
            <h4 class="subtitle is-6 has-text-grey-light">No need of registration.</h4>
        </div>
        <div class="column">
            <h3 class="title is-4 has-text-centered">For (YOU)</h3>
            <h4 class="subtitle is-6 has-text-grey-light">UUUU</h4>
        </div>
    </section>

{% endblock %}

dnshare/blueprints/default/templates/default/my_domains.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field_errors, render_flashed_messages %}
{% block body %}

    <div class="box" id="home-registration-form">
        {{ render_flashed_messages() }}

        <h1 class="title is-3">
            Claimable registrations
        </h1>
        <h2 class="subtitle is-5">
            Registrations made from your IP, but not while logged-in.
        </h2>

        <table class="table is-fullwidth is-striped">
            <thead>
            <tr>
                <th>Domain</th>
                <th>Host IP</th>
                <th>Registration date (UTC)</th>
                <th>Expiration date (UTC)</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for registration in claimable %}
                <tr>
                    <td>{{ registration.subdomain }}.{{ registration.domain }}</td>
                    <td>{{ registration.host_ip }}</td>
                    <td>{{ registration.creation_date_utc }}</td>
                    <td>{{ registration.expiration_date_utc }}</td>
                    <td>
                        <form action="{{ url_for('default.claim') }}" method="post">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <input type="hidden" name="registration_id" value="{{ registration.id }}">
                            <button class="button is-primary is-small" type="submit">
                                Claim
                            </button>
                        </form>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5" class="has-text-centered has-text-grey-light">
                        There are no claimable registrations.
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <h1 class="title is-3">
            Active registrations
        </h1>

        <table class="table is-fullwidth is-striped">
            <thead>
            <tr>
                <th>Domain</th>
                <th>Host IP</th>
                <th>Registration date (UTC)</th>
                <th>Expiration date (UTC)</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for registration in active %}
                <tr>
                    <td>{{ registration.subdomain }}.{{ registration.domain }}</td>
                    <td>{{ registration.host_ip }}</td>
                    <td>{{ registration.creation_date_utc }}</td>
                    <td>{{ registration.expiration_date_utc }}</td>
                    <td>
                        <div class="field has-addons">
                            <p class="control">
                                <a class="button is-small" disabled="disabled">
                                    Edit
                                </a>
                            </p>
                            <p class="control">
                            <form action="{{ url_for('default.delete') }}" method="post">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                <input type="hidden" name="registration_id"
                                       value="{{ registration.id }}">
                                <button class="button is-danger is-small js-delete-registration"
                                        data-registration-id="{{ registration.id }}">
                                    Delete
                                </button>
                            </form>
                            </p>
                        </div>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5" class="has-text-centered has-text-grey-light">
                        There are no active registrations.
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ url_for('default.home') }}" class="button is-primary is-medium is-pulled-right">
            Create New Registration
        </a>
        <span class="is-clearfix"></span>
    </div>

{% endblock %}
{% block scripts %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const deleteRegistrationBtns = document.querySelectorAll('.js-delete-registration');
            deleteRegistrationBtns.forEach(function (el) {
                el.addEventListener('click', function (evt) {
                    const deletionConfirmed = confirm('Are you sure you want to delete this registration?');
                    if (!deletionConfirmed) evt.preventDefault();
                });
            });
        });
    </script>
{% endblock %}

dnshare/blueprints/default/templates/default/privacy.html
{% extends "layout.html" %}
{% block body %}

    <h1 class="title is-3">
        Privacy Policy
    </h1>
    <h2 class="subtitle is-5">
        What data we store, and with whom we share that data.
    </h2>

    <section class="content">
        <blockquote>
            <strong>TL;DR:</strong> We store your IP, and if you give it to us: your email.
            Your data is never given in any form to third parties, except upon legally
            valid requests made in the US (where the servers are) or Chile (where I'm).
        </blockquote>

        <h3>What we always collect</h3>

        <p>
            When you create a domain, we store your public IP together with the rest of
            the domain registration info. No further fingerprinting is performed.
        </p>

        <p>
            This information is mainly stored so you can make changes in your anonymously
            registered subdomains as long as you visit the site from the same IP as when
            you created them.
        </p>

        <h3>What we collect when you create an account</h3>

        <p>
            When you create an account, you may optionally enter your email to provide a
            way for you to recover your password in if you need to do so. We also store
            your public IP when you create the account. We don't store further login and
            logout data.
        </p>

        <h3>With whom we share your data</h3>

        <p>
            We don't give your data to any third party, ever... except, of
            course, when that third party has a legally valid (in the US or Chile)
            warrant for the data. I'm sorry for that, but saying otherwise would be to
            lie.
        </p>

        <h3>Anything else?</h3>

        <p>
            If you have any further questions, please consider sending me an email at
            <code>cristian [at] dnshare.org</code>.
        </p>
    </section>

{% endblock %}