dnshare/blueprints/default/views.py
from flask import Blueprint, render_template, make_response, flash, \
    redirect, url_for, request
from flask_login import current_user, login_required

from dnshare.gateways import InvalidIPv4HostAddress, InvalidSubdomainError
from .application import register_subdomain, registration_overriden, \
    SubdomainAlreadyTaken, RegistrationLimitSurpassed, \
    get_claimable_registrations, get_user_registrations, claim_anon_registration, \
    delete_registration
from .forms import AnonRegisterForm, ClaimForm, DeleteForm

default = Blueprint('default', __name__, template_folder='templates')

SUBMIT_ERROR_MSG = ('It appears that there are some errors with your '
                    'registration. Please check and try again.')
REGISTRATION_OK_TPL = ('{subdomain}.{domain} was successfully '
                       'registered to resolve to {host_ip}.')
TOO_MANY_REGISTRATIONS_MSG = 'You have registered quite a few domains today. Please try again tomorrow.'
NGGYU_URL = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'
INVALID_HOST_TPL = ('The host "{host}" apparently is not a valid IPv4. '
                    'Please check that and try again.')
INVALID_SUBDOMAIN_TPL = ('The subdomain "{subdomain}" doesn\'t appear to be '
                         'a valid subdomain. Please check that and try again.')


@default.route("/", methods=['GET'])
def home():
    form = _create_anon_register_form()
    remote_ip = request.remote_addr

    return render_template('default/home.html', form=form, remote_ip=remote_ip)


@default.route('/', methods=['POST'])
def register_anon_host():
    form = _create_anon_register_form()
    if not form.validate():
        if "protected_subdomain" in form.subdomain.errors:
            return redirect(NGGYU_URL)

        home_page = render_template('default/home.html', form=form)
        return make_response(home_page, 400)

    subdomain = form.subdomain.data
    domain = form.domain.data
    host_ip = form.host_ip.data
    creator_ip = request.environ.get('HTTP_X_REAL_IP', request.remote_addr)

    def handle_reregistration(sender, old_host_ip):
        msg = _create_override_msg(subdomain, domain, old_host_ip, host_ip)
        flash(msg, 'info')

    registration_overriden.connect(handle_reregistration)

    try:
        is_anon = current_user.is_anonymous
        register_subdomain(subdomain, domain, host_ip, creator_ip,
                           None if is_anon else current_user)
    except SubdomainAlreadyTaken:
        taken_msg = _create_already_taken_msg(subdomain, domain)
        flash(taken_msg, 'error')
        return redirect(url_for('default.home'))
    except RegistrationLimitSurpassed:
        flash(TOO_MANY_REGISTRATIONS_MSG, 'error')
        return redirect(url_for('default.home'))
    except InvalidIPv4HostAddress:
        host_error = _create_invalid_host_msg(host_ip)
        flash(host_error, 'error')
        return redirect(url_for('default.home'))
    except InvalidSubdomainError:
        error = _create_invalid_subdomain_msg(subdomain)
        flash(error, 'error')
        return redirect(url_for('default.home'))

    success_message = _create_success_msg(
        form.subdomain.data, form.domain.data, form.host_ip.data)
    flash(success_message, 'success')

    return redirect(url_for('default.home'))


@default.route('/registrations', methods=['GET'])
@login_required
def registrations():
    user_ip = request.environ.get('HTTP_X_REAL_IP', request.remote_addr)
    user_id = current_user.id

    claimable_registrations = get_claimable_registrations(user_ip)
    active_registrations = get_user_registrations(user_id)

    return render_template('default/my_domains.html',
                           claimable=claimable_registrations,
                           active=active_registrations)


@default.route('/claim', methods=['POST'])
@login_required
def claim():
    user_ip = request.environ.get('HTTP_X_REAL_IP', request.remote_addr)
    user_id = current_user.id

    form = ClaimForm()
    if form.validate():
        claim_anon_registration(user_id, user_ip, form.registration_id.data)

    flash('Registration has been claimed successfully!', 'success')
    return redirect(url_for('default.registrations'))


@default.route('/delete', methods=['POST'])
@login_required
def delete():
    user_id = current_user.id

    form = DeleteForm()
    if form.validate():
        delete_registration(user_id, form.registration_id.data)

    flash('Registration has been deleted. Change may take up to 1 hour '
          'to propagate to DNS servers due to DNS caching.', 'success')
    return redirect(url_for('default.registrations'))


@default.route('/about', methods=['GET'])
def about():
    return render_template('default/about.html')


@default.route('/privacy', methods=['GET'])
def privacy():
    return render_template('default/privacy.html')


def _create_anon_register_form():
    form = AnonRegisterForm()
    form.domain.choices = [(d, d) for d in _get_available_domains()]
    return form


def _get_available_domains():
    """Get all available domains for which a user can register a
    subdomain. Currently hardcoded."""
    return ["dnshare.org"]


def _create_success_msg(subdomain, domain, host_ip):
    return REGISTRATION_OK_TPL.format(**locals())


def _create_override_msg(subdomain, domain, old_ip, new_ip):
    return (f'{subdomain}.{domain} updated! Previously it resolved to '
            f'{old_ip}, now it resolves to {new_ip}.')


def _create_already_taken_msg(subdomain, domain):
    return (f'{subdomain}.{domain} is already registered and active. '
            'Please choose other subdomain and domain combination.')


def _create_invalid_host_msg(host_ip):
    return INVALID_HOST_TPL.format(host=host_ip)


def _create_invalid_subdomain_msg(subdomain):
    return INVALID_SUBDOMAIN_TPL.format(subdomain=subdomain)

dnshare/blueprints/user/views.py
from flask import Blueprint, request, redirect, url_for, flash, render_template
from flask_login import login_user, login_required, logout_user, current_user

from dnshare.blueprints.user.application import send_password_reset_email
from dnshare.extensions import db, csrf
from .decorators import anonymous_required
from .forms import LoginForm, SignupForm, SettingsForm, BeginPasswordResetForm, ResetPasswordForm
from .models import User

user = Blueprint('user', __name__, template_folder='templates')


@user.route('/login', methods=['GET', 'POST'])
@anonymous_required()
def login():
    form = LoginForm(next=request.args.get('next'))

    if form.validate_on_submit():
        u = User.query.filter_by(email=request.form.get('email')).first()

        if u and u.has_password(request.form.get('password')):
            if login_user(u, remember=True) and u.is_active():
                u.update_activity_tracking(request.remote_addr)

                # Handle optionally redirecting to the next URL safely.
                next_url = request.form.get('next')
                if next_url:
                    return redirect(next_url)

                return redirect(url_for('default.home'))
            else:
                flash('This account has been disabled.', 'error')
        else:
            flash('Email or password is incorrect.', 'error')

    return render_template('user/login.html', form=form)


@user.route('/logout', methods=['POST'])
@login_required
@csrf.exempt
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('user.login'))


@user.route('/signup', methods=['GET', 'POST'])
@anonymous_required()
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        u = User()

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        db.session.add(u)
        db.session.commit()

        if login_user(u):
            flash('Registration complete. Thanks for signing up.', 'success')
            return redirect(url_for('default.home'))

    return render_template('user/signup.html', form=form)


@user.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    form = SettingsForm()

    if form.is_submitted():
        if form.validate():
            current_user.email = form.email.data

            new_password = form.new_password.data
            if new_password:
                current_user.password = User.encrypt_password(new_password)

            db.session.commit()

            flash('Account settings updated.', 'success')
            return redirect(url_for('user.settings'))

    else:
        form.email.data = current_user.email

    return render_template('user/settings.html', form=form)


@user.route('/forgot-password', methods=['GET', 'POST'])
def begin_password_reset():
    form = BeginPasswordResetForm()

    if form.validate_on_submit():
        email = form.email.data
        send_password_reset_email(email)

        flash('An email has been sent to {0}.'.format(email), 'success')
        return redirect(url_for('user.login'))

    return render_template('user/begin_password_reset.html', form=form)


@user.route('/reset-password', methods=['GET', 'POST'])
def reset_password():
    form = ResetPasswordForm(reset_token=request.args.get('reset_token'))

    if form.validate_on_submit():
        u = User.deserialize_token(request.form.get('reset_token'))

        if u is None:
            flash('Your reset token has expired or was tampered with.',
                  'error')
            return redirect(url_for('user.begin_password_reset'))

        u.password = User.encrypt_password(request.form.get('password'))
        db.session.commit()

        flash('Your password has been reset.', 'success')
        return redirect(url_for('user.login'))

    return render_template('user/reset_password.html', form=form)

dnshare/templates/_form_macros.html
{% macro render_field_errors(form) %}
    {% if form.errors %}

        <div class="notification is-danger">
            <button class="delete"></button>
            <ul>
                {% for field in form.errors %}
                    {% for error in form.errors[field] %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>

    {% endif %}
{% endmacro %}

{% macro render_flashed_messages() %}

    {% for error_message in get_flashed_messages(category_filter=["error"]) %}
        <div class="notification is-warning">
            <button class="delete"></button>
            <p>{{ error_message }}</p>
        </div>
    {% endfor %}
    {% for success_message in get_flashed_messages(category_filter=["success"]) %}
        <div class="notification is-success">
            <button class="delete"></button>
            <p>{{ success_message }}</p>
        </div>
    {% endfor %}
    {% for info_message in get_flashed_messages(category_filter=["info"]) %}
        <div class="notification is-info">
            <button class="delete"></button>
            <p>{{ info_message }}</p>
        </div>
    {% endfor %}

{% endmacro %}

dnshare/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
          integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    <title>DNShare</title>
    <style>
        body {
            background-image: url("{{ url_for('static', filename='bg.png') }}");
        }
    </style>
</head>

<body>
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
    <div class="container">
        <div class="navbar-brand">
            <a href="{{ url_for('default.home') }}" class="navbar-item">
                <h1 class="title">
                    <span class="has-text-dark">DNShare</span><span class="has-text-primary">.org</span>
                </h1>
            </a>

            <div class="navbar-item is-hidden-touch">
                <p class="has-text-grey-dark">Free, temporary, and anonymous. A-host registration.</p>
            </div>

            <div class="navbar-burger burger" data-target="menu">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>

        <div class="navbar-menu" id="menu">
            <div class="navbar-end">
                <a class="navbar-item" href="{{ url_for('default.about') }}">
                    About
                </a>
                <a class="navbar-item" href="{{ url_for('default.privacy') }}">
                    Privacy
                </a>

                {% if current_user.is_authenticated %}
                    <a class="navbar-item" href="{{ url_for('default.registrations') }}">
                        My domains
                    </a>
                    <a class="navbar-item" href="{{ url_for('user.settings') }}">
                        My account
                    </a>
                    <a class="navbar-item js-logout" href="#">
                        Sign-out
                    </a>
                {% else %}
                    <a class="navbar-item" href="{{ url_for('user.login') }}">
                        Sign-in
                    </a>

                    <div class="navbar-item">
                        <div class="field">
                            <a class="button is-primary" href="{{ url_for('user.signup') }}">
                                Sign-up
                            </a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

<div class="container" id="content">
    {% block body %}
    {% endblock %}
</div>

<footer class="footer">
    <div class="content has-text-centered">
        <div class="container">
            <p>
                Source code is available at <a href="https://gitlab.com/cristianof/dnshare">GitLab</a>
                under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">AGPLv3 license</a>.
            </p>
        </div>
    </div>
    <form id="logout-form" action="{{ url_for('user.logout') }}" method="post"></form>
</footer>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const logoutTrigger = document.querySelector('.js-logout');
        const logoutForm = document.getElementById('logout-form');
        logoutTrigger && logoutTrigger.addEventListener('click', function () {
            logoutForm.submit();
        });

        const deleteButtons = document.querySelectorAll('.delete');
        deleteButtons.forEach(function (el) {
            el.addEventListener('click', function () {
                el.parentElement.remove();
            });
        });

        const burgers = document.querySelectorAll('.navbar-burger');
        burgers.forEach(function (el) {
            el.addEventListener('click', () => {
                // Get the target from the "data-target" attribute
                const target = el.dataset.target;
                const $target = document.getElementById(target);

                // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                el.classList.toggle('is-active');
                $target.classList.toggle('is-active');
            });
        });
    });

    function postData(url = ``, data = {}) {
        return fetch(url, {
            method: "POST",
            headers: {
                "Content-Type": "application/json; charset=utf-8",
            },
            body: JSON.stringify(data),
        }).then(response => response.json());
    }
</script>
{% block scripts %}
{% endblock %}

</body>
</html>